version: 2.0
jobs:
  build:
    docker:
      - image: ajmasiaa/carta-backend-builder-ubuntu

    steps:
      - checkout
      - run: ls -sort
      - run: git submodule init
      - run: git submodule update
      - run: ls -sort        
      - run: mkdir build && cd build && cmake .. && make && ls
