version: 2.0
jobs:
  build:
    docker:
      - image: ajmasiaa/carta-backend-builder-ubuntu

    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule add https://github.com/idia-astro/carta-protobuf
            git submodule init
            git submodule update
      - run:
          name: "Build"
          command: mkdir build && cd build && cmake .. && make && ls
