version: 2.0
jobs:
  build:
    docker:
      - image: ajmasiaa/carta-backend-builder-ubuntu
    steps:
      - checkout
      - run:
          name: "submodules"
          command: |
            git submodule add https://github.com/idia-astro/carta-protobuf
            git submodule init
            git submodule update
      - run:
          name: "build ubuntu version"
          command: mkdir build && cd build && cmake .. && make && ls
  build:
    docker:
      - image: ajmasiaa/carta-backend-builder-centos6
    steps:
      - checkout
      - run:
          name: "submodules"
          command: |
            git submodule add https://github.com/idia-astro/carta-protobuf
            git submodule init
            git submodule update
      - run:
          name: "build CentOS6 version"
          command: mkdir build && cd build && cmake .. && make && ls
